name: CD

on:
  pull_request:
    branches:
      - '**'

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workerDirectory:
          - workers/a
          - workers/b

    steps:
      # env stuff
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: node - setup
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: diff changes
        run: echo "CHANGES_DETECTED=$(git diff origin/main --name-only ${{matrix.workerDirectory}})" >> $GITHUB_ENV

      - name: deploy
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        if: env.CHANGES_DETECTED
