name: CD

on:
  pull_request:
    branches:
      - '**'

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workerDirectory:
          - workers/a
          - workers/b

    outputs:
      CHANGED_WORKERS: ${{ steps.reporter.outputs.CHANGED_WORKERS }}

    steps:
      # env stuff
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: node - setup
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Has package.json
        run: test -e 'workers/a/package.json' && echo 'HAS_PACKAGE_JSON=true' >> $GITHUB_ENV || echo 'Invalid package'

      - name: Detect changes
        run: echo "CHANGES_DETECTED=\"$(git diff HEAD~1 --name-only ${{matrix.workerDirectory}})\"" >> $GITHUB_ENV

      - name: Report deployments
        if: env.CHANGES_DETECTED
        run: echo "Changes detected, worker will deploy upon merge" >> $GITHUB_STEP_SUMMARY
